import type { Metadata } from "next";
import { LegalShell } from "../LegalShell";

export const metadata: Metadata = {
  title: "Terms of Service — snapp",
};

const CONTACT_EMAIL = "realmrzhang@gmail.com";

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" effective="July 16, 2026">
      <p>
        These terms are an agreement between you and snapp (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;) covering your use of the snapp website and app. By
        creating an account or using snapp you agree to them. If you
        don&apos;t agree, please don&apos;t use snapp.
      </p>

      <h2>1. What snapp is</h2>
      <p>
        snapp is a visual bookmark manager for websites, with a paid feature
        (&ldquo;Mix&rdquo;) that analyzes the sites you save — capturing
        screenshots, fonts, and colors — and uses AI to generate a written
        design brief from the sources and notes you choose.
      </p>

      <h2>2. Your account</h2>
      <p>
        You need an account to use the app. You can sign up with an email and
        password or with Google. You&apos;re responsible for activity on your
        account and for keeping your credentials secure. You must be at least
        13 years old (or the minimum age of digital consent where you live).
      </p>

      <h2>3. Free plan and Pro subscription</h2>
      <ul>
        <li>
          <strong>Free</strong> — saving and organizing bookmarks is free and
          unlimited. Free accounts include a monthly allowance of metered
          actions (design briefs, site analyses, and deep scans).
        </li>
        <li>
          <strong>Pro</strong> — a paid monthly subscription (currently
          US$12/month) with much higher monthly allowances. Payments are
          processed by <strong>Stripe</strong>; we never see or store your
          card number. Subscriptions renew automatically each month until you
          cancel. You can cancel anytime from Settings → Manage billing, and
          you keep Pro until the end of the paid period. See our{" "}
          <a href="/refunds">refund policy</a>.
        </li>
      </ul>
      <p>
        We may change prices or allowances going forward; if we do, we&apos;ll
        give existing subscribers reasonable notice before a change affects
        them.
      </p>

      <h2>4. Fair use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          use snapp&apos;s scanning to overload, attack, or circumvent access
          controls of any website, or to scan sites you have no right to
          access;
        </li>
        <li>
          attempt to bypass usage limits, resell metered actions, or access
          other users&apos; data;
        </li>
        <li>
          use snapp for anything unlawful, or upload content that infringes
          someone else&apos;s rights.
        </li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate these rules or that
        create abnormal load or cost.
      </p>

      <h2>5. Your content and generated briefs</h2>
      <p>
        You own your bookmarks, notes, and the design briefs generated for
        you. You grant us the limited rights needed to operate the service
        (storing, processing, and displaying your content back to you).
        Screenshots and extracted data from third-party websites are captured
        at your direction for your personal reference and analysis; the
        underlying sites remain the property of their owners, and your use of
        that material is your responsibility.
      </p>

      <h2>6. AI output</h2>
      <p>
        Design briefs are generated by an AI model (Anthropic&apos;s Claude)
        from the sources and notes you select. AI output can be wrong,
        incomplete, or similar to output generated for others. It&apos;s
        provided as a starting point, not professional advice, and you&apos;re
        responsible for how you use it.
      </p>

      <h2>7. Disclaimer and limitation of liability</h2>
      <p>
        snapp is provided &ldquo;as is&rdquo; without warranties of any kind.
        To the maximum extent permitted by law, we are not liable for
        indirect, incidental, or consequential damages, and our total
        liability for any claim is limited to the amount you paid us in the
        twelve months before the claim arose (or US$20 if you paid nothing).
        Nothing in these terms excludes liability that can&apos;t be excluded
        by law.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can stop using snapp and delete your account at any time by
        contacting us. We may suspend or close accounts that break these
        terms. On termination, your subscription ends per the refund policy
        and we&apos;ll delete your data as described in the{" "}
        <a href="/privacy">privacy policy</a>.
      </p>

      <h2>9. Changes</h2>
      <p>
        We may update these terms as snapp evolves. For material changes
        we&apos;ll notify you (for example by email or an in-app notice)
        before they take effect. Continuing to use snapp after a change means
        you accept the new terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
    </LegalShell>
  );
}
